## Cargando librerias necesarias

In [1]:
import kagglehub
import pandas as pd
from pathlib import Path

## Descarga del dataset

In [2]:
path = kagglehub.dataset_download(
    "sdeogade/sparse-industrial-machine-time-series-dataset"
)

print(path)

Downloading to C:\Users\usuario\.cache\kagglehub\datasets\sdeogade\sparse-industrial-machine-time-series-dataset\1.archive...

100%|██████████| 4.49M/4.49M [00:01<00:00, 3.64MB/s]

Extracting files...

C:\Users\usuario\.cache\kagglehub\datasets\sdeogade\sparse-industrial-machine-time-series-dataset\versions\1

In [3]:
from pathlib import Path

dataset_path = Path(path)

for file in dataset_path.iterdir():
    print(file.name)

synthetic_industrial_machine_data.csv

## 1 . Carga de los datos

In [4]:
csv_file = next(dataset_path.glob("*.csv"))

df = pd.read_csv(csv_file)

df.head()

,transaction_date,asset_tag,machine_type,plant_code,part_no,part_description,part_family,criticality,uom,unit_cost_inr,...,temp_bearing_degC,temp_motor_degC,vibration_h_mms,vibration_v_mms,oil_pressure_bar,load_pct,shaft_rpm,power_consumption_kw,breakdown_flag,wo_type
0,2022-01-03,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,63.3,63.5,4.944,3.886,3.71,85.9,1794,16.09,0,NaN
1,2022-01-04,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.0,64.8,4.614,3.530,3.67,82.0,1790,15.53,0,NaN
2,2022-01-05,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.4,66.7,4.360,2.976,3.74,83.0,1827,16.20,0,NaN
3,2022-01-06,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,64.5,68.1,4.522,3.315,3.90,82.9,1811,16.47,0,NaN
4,2022-01-07,AST-1041,CNC Lathe,PUN-01,MRO-10045,Deep Groove Ball Bearing 6205-2RS,Bearing,A,EA,850,...,62.2,66.3,4.340,3.434,3.71,80.1,1810,15.08,0,NaN

### Shape

In [5]:
df.shape

(219000, 22)

### Tipos de datos

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 219000 entries, 0 to 218999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_date      219000 non-null  str
 1   asset_tag             219000 non-null  str
 2   machine_type          219000 non-null  str
 3   plant_code            219000 non-null  str
 4   part_no               219000 non-null  str
 5   part_description      219000 non-null  str
 6   part_family           219000 non-null  str
 7   criticality           219000 non-null  str
 8   uom                   219000 non-null  str
 9   unit_cost_inr         219000 non-null  int64
 10  qty_issued            219000 non-null  int64
 11  issue_value_inr       219000 non-null  int64
 12  temp_bearing_degC     219000 non-null  float64
 13  temp_motor_degC       219000 non-null  float64
 14  vibration_h_mms       219000 non-null  float64
 15  vibration_v_mms       219000 non-null  float64
 16  oil_pressure_bar      219000 non-null  float64
 17  load_pct              219000 non-null  float64
 18  shaft_rpm             219000 non-null  int64
 19  power_consumption_kw  219000 non-null  float64
 20  breakdown_flag        219000 non-null  int64
 21  wo_type               42793 non-null   str
dtypes: float64(7), int64(5), str(10)
memory usage: 36.8 MB

### Nulos por columna en el dataset

In [7]:
df.isna().sum()

transaction_date             0
asset_tag                    0
machine_type                 0
plant_code                   0
part_no                      0
part_description             0
part_family                  0
criticality                  0
uom                          0
unit_cost_inr                0
qty_issued                   0
issue_value_inr              0
temp_bearing_degC            0
temp_motor_degC              0
vibration_h_mms              0
vibration_v_mms              0
oil_pressure_bar             0
load_pct                     0
shaft_rpm                    0
power_consumption_kw         0
breakdown_flag               0
wo_type                 176207
dtype: int64

### Duplicados

In [8]:
df.duplicated().sum()

np.int64(0)

### Estadísticos Básicos

In [9]:
df.describe()

,unit_cost_inr,qty_issued,issue_value_inr,temp_bearing_degC,temp_motor_degC,vibration_h_mms,vibration_v_mms,oil_pressure_bar,load_pct,shaft_rpm,power_consumption_kw,breakdown_flag
count,219000.000000,219000.000000,219000.000000,219000.000000,219000.000000,219000.000000,219000.000000,219000.000000,219000.00000,219000.000000,219000.000000,219000.000000
mean,814.750000,0.120447,60.917557,65.100146,71.088137,3.869373,2.900656,5.010040,68.34390,1553.652785,26.456038,0.098795
std,793.329983,0.444104,294.269538,4.919569,6.897467,1.345510,1.026620,0.951498,12.18837,773.344112,19.278766,0.298387
min,12.000000,0.000000,0.000000,43.500000,49.800000,0.671000,0.401000,3.300000,34.20000,654.000000,4.430000,0.000000
25%,203.750000,0.000000,0.000000,63.700000,65.100000,3.083000,2.291000,4.120000,58.90000,931.000000,13.070000,0.000000
50%,660.000000,0.000000,0.000000,66.300000,71.500000,3.618500,2.736000,4.940000,68.80000,1437.000000,16.730000,0.000000
75%,965.000000,0.000000,0.000000,68.300000,77.000000,4.395000,3.309000,5.450000,79.10000,1810.000000,38.520000,0.000000
max,3200.000000,7.000000,3200.000000,73.500000,88.400000,13.305000,10.088000,7.390000,95.40000,2980.000000,82.500000,1.000000

### Variables Categóricas

In [10]:
df.select_dtypes(include=["object"]).nunique()

C:\Users\usuario\AppData\Local\Temp\ipykernel_19276\3900290564.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object"]).nunique()

transaction_date    1095
asset_tag             10
machine_type           5
plant_code             3
part_no               20
part_description      20
part_family            9
criticality            3
uom                    5
wo_type                2
dtype: int64